Controllers/ClientesController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PowerAutomate.Core;
using PowerAutomate.Core.Entities;

namespace PowerAutomate.Controllers
{
    [Authorize(Roles="Administrator")]
    public class ClientesController: Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<ClientesController> _logger;

        public ClientesController(ILogger<ClientesController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }
        
        public IActionResult Index()
        {
            Clientes cliente = new Clientes();
            ViewBag.Clientes = _context.Clientes.ToList();
            return View(cliente);
        }

        [BindProperty]
        public Clientes Cliente {get;set;}
        public IActionResult Guardar()
        {
            if(!ModelState.IsValid)
                {
                    return Redirect("/Clientes/");
                }
                var _Cliente = _context.Clientes.Where(x=> x.IdCliente == Cliente.IdCliente).SingleOrDefault();
                if (_Cliente== null)
                {
                    _context.Clientes.Add(Cliente);
                }
                else
                {
                    _Cliente.Nombre = Cliente.Nombre;
                    _Cliente.Dni= Cliente.Dni;
                    _Cliente.Correo = Cliente.Correo;
                }
                _context.SaveChanges();
                return RedirectToAction("Index");
        }

        public IActionResult Modificar(int id)
        {
            var cliente = _context.Clientes.Find(id);
            if(cliente == null)
            {
                return Redirect("/Clientes/");
            }

            return View(cliente);
        }

        public IActionResult Eliminar(int id)
        {
            var cliente= _context.Clientes.Find(id);
            if(cliente== null)
            {
                return StatusCode(404);
            }

            _context.Clientes.Remove(cliente);
            _context.SaveChanges();
            
            return Redirect("/Clientes/");;
        }

            public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ComprasController.cs
using System.Xml.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Reflection.PortableExecutable;
using System.ComponentModel.Design;
using System.Text;
using System.Data;
using System.Runtime.InteropServices;
using System.Data.Common;
using System.Reflection.Metadata;
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PowerAutomate.Core;
using PowerAutomate.Core.Entities;
using Microsoft.AspNetCore.Authorization;

namespace PowerAutomate.Controllers;
[Authorize]
public class ComprasController: Controller
{
    Response res= new Response();
    ApplicationDbContext _context;
    private readonly ILogger<ComprasController> _logger;

    public ComprasController(ILogger<ComprasController> logger, ApplicationDbContext context)
    {
        _logger = logger;
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        ViewBag.Compra = await _context.Compras.Include("DetalleCompra").Include(x=>x.Proveedor).ToListAsync();
        return View();
    }

    public async Task<IActionResult> Nuevo(int? id)
    {
            var IdCompra = id ?? 0;
            var _Compra = await _context.Compras.FindAsync(IdCompra);
            var Compra = new Compras();
            if(_Compra != null)
            {
                Compra = _Compra;
            }
            ViewBag.Proveedores = await _context.Proveedores.ToListAsync();
            ViewBag.Productos = await _context.Productos.Select(x=>new{x.IdProducto, NombreProducto= x.Nombre + " - " + x.Marca}).ToListAsync();
            Tuple<Compras, DetalleCompra> Model = new Tuple<Compras, DetalleCompra>(new Compras(), new DetalleCompra());
            ViewBag.DetalleCompra= await _context.DetalleCompra.Include(x=>x.Producto).Where(x=>x.IdCompra == IdCompra).ToListAsync();
            return View(Model);
    }
    public async Task<IActionResult> SetEncabezado([Bind(Prefix="Item1")] Compras Compra)
        {
            // if(!ModelState.IsValid)
            // {
            //     res.estado = false;
            //     res.mensaje = "Rellene los campos solicitados.";
            //     return Json(res);
            // }
            var _Compra = await _context.Compras.FindAsync(Compra.IdCompra);
            if(_Compra == null)
            {
                _context.Compras.Add(Compra);
                await _context.SaveChangesAsync();
            }
            else
            {
                _Compra.IdProveedor = Compra.IdProveedor;
                _Compra.NumeroFactura = Compra.NumeroFactura;
                await _context.SaveChangesAsync();
            }
            res.resultado = Compra.IdCompra;
            res.estado = true;
            return Json(res);
        }
    
        public async Task<IActionResult> SetDetalle([Bind(Prefix="Item2")] DetalleCompra Detalle)
        {
            // if(!ModelState.IsValid)
            // {
            //     res.estado= false;
            //     res.mensaje= "Rellene los campos Solicitados.";
            //     return Json(res);
            // }
            Detalle.Iva= Detalle.Cantidad * Detalle.Precio * 0.21M;
            Detalle.Total= Detalle.Iva + Convert.ToDecimal(Detalle.Cantidad * Detalle.Precio);
            _context.DetalleCompra.Add(Detalle);
            await _context.SaveChangesAsync();
            Detalle.Producto= await _context.Productos.FindAsync(Detalle.IdProducto);
            Detalle.Producto.Precio= Detalle.Precio * Convert.ToDecimal(1.50);
            Detalle.Producto.Stock= Detalle.Producto.Stock + Detalle.Cantidad;
            res.resultado= Detalle;
            res.mensaje= "El producto ha sido agregado";
            res.estado = true;
            return Json(res);
        }

   

        public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/LoginController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json.Linq;
using PowerAutomate.Core;
using PowerAutomate.Core.Entities;
using PowerAutomate.Core.ViewModel;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using System.Security.Claims;
using PowerAutomate.Core.Helpers;
using System.Text;


namespace PowerAutomate.Controllers;

public class LoginController : Controller
{
    private readonly IConfiguration _config;
    private readonly ILogger<HomeController> _logger;
    ApplicationDbContext _context;

     public LoginController(ILogger<HomeController> logger, ApplicationDbContext context, IConfiguration config)
    {
        _logger = logger;
        _context = context;
        _config = config;
    }

    public IActionResult Index()
    {
        if (User.Identity.IsAuthenticated)
        {
            return Redirect("/Home");
        }
        else
        {
        return View();
        }
    }
    public async Task<IActionResult> Login([Bind] UserVm Useuario)
    {
        if (!ModelState.IsValid)
        {
            return BadRequest(new JObject() {
                    { "StatusCode", 400 },
                    { "Message", "El usuario ya existe, seleccione otro." }
                });
        }
        else
        {
            var result= await _context.User.Include("Role").Where(x=> x.Email == Useuario.Email).SingleOrDefaultAsync();
            if (result == null)
            {
                return NotFound(new JObject() {
                    { "StatusCode", 400 },
                    { "Message", "Usuario no encontrado" }
                });
            }
            else
            {
                if (Encrypt.Verify(Useuario.Password, result.Password))
                {
                //        var secretKey = _config.GetValue<string>("SecretKey");
                //     var key = Encoding.ASCII.GetBytes(secretKey);

                // var claims = new ClaimsIdentity();
                // claims.AddClaim(new Claim(ClaimTypes.NameIdentifier, Useuario.Email));

                // var tokenDescriptor = new SecurityTokenDescriptor
                // {
                //     Subject = claims,
                //     Expires = DateTime.UtcNow.AddHours(4),
                //     SigningCredentials = new SigningCredentials(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha256Signature)
                // };

                // var tokenHandler = new JwtSecurityTokenHandler();
                // var createdToken = tokenHandler.CreateToken(tokenDescriptor);
                
                // string bearer_token = tokenHandler.WriteToken(createdToken);
                // return Ok(bearer_token);
                  var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme, ClaimTypes.Email, ClaimTypes.Role);
                        identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, result.Id.ToString()));
                        identity.AddClaim(new Claim(ClaimTypes.Email, result.Email));
                        identity.AddClaim(new Claim(ClaimTypes.Role, result.Role.Name));
                        // identity.AddClaim(new Claim(ClaimTypes.Email, "jose.jairo.fuentes@gmail.com"));
                        identity.AddClaim(new Claim("Dato", "Valor"));
                        var principal = new ClaimsPrincipal(identity);
                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal,
                            new AuthenticationProperties { ExpiresUtc = DateTime.Now.AddDays(2), IsPersistent = true });
                        return Ok(result);
                }
                else
                {
                    var response = new JObject() {
                            { "StatusCode", 403 },
                            { "Message", "Usuario o contraseña no válida." }
                        };
                        return StatusCode(403, response);
                }
            }
        }
    }
  
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        return Redirect("/Login");
    }
    

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/ProductosController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PowerAutomate.Core;
using PowerAutomate.Core.Entities;

namespace PowerAutomate.Controllers;
[Authorize]
public class ProductosController : Controller
{

    ApplicationDbContext _context;

    public ProductosController( ApplicationDbContext context)
    {
        _context = context;
    }

        public async Task<IActionResult> Index()
        {
            List<Productos> Productos = await _context.Productos.Include(x=>x.Categoria).ToListAsync();
            Productos Producto = new Productos();
            ViewBag.Productos = Productos;
            ViewBag.Categorias = await _context.Categorias.ToListAsync();
            return View(Producto);
        }

        [BindProperty]
        public Productos Producto {get; set;}
        public async Task<IActionResult> SetProducto()
        {   
           
            var _Producto = await _context.Productos.Where(x=>x.IdProducto == Producto.IdProducto).AnyAsync();
            if(!_Producto)
            {
                _context.Productos.Add(Producto);
            }
            else
            {
                _context.Productos.Attach(Producto);
                _context.Entry(Producto).State = EntityState.Modified;
            }            
            await _context.SaveChangesAsync();
            return Redirect("/Productos");
        }

          public async Task<IActionResult> Modificar(int id)
        {
            var Producto = await _context.Productos.FindAsync(id);
            if(Producto == null)
            {
                return RedirectToAction("Index");
            }
            ViewBag.Categorias = await _context.Categorias.OrderBy(x=>x.Categoria).ToListAsync();
            return View(Producto);
        }

        
        public async Task<IActionResult> Eliminar(int id)
        {
            var _Producto = await _context.Productos.FindAsync(id);
            if(_Producto == null)
            {
                return RedirectToAction("Index");
            }
            else
                _context.Productos.Remove(_Producto);
                _context.SaveChanges();
            return RedirectToAction("Index");
        }

        

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Shared/_Layout.cshtml
@using PowerAutomate.Core.Helpers
<!DOCTYPE html
 PUBLIC "-//W3C//DTD HTML 4.01//EN"
      "http://www.w3.org/TR/html4/strict.dtd"
>
<html lang="en">
    
<head profile="http://www.w3.org/2005/10/profile">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DataNet</title>
    <link rel="icon" type="image/png"  href="https://www.google.com/imgres?imgurl=https%3A%2F%2Flh3.googleusercontent.com%2FCClor8cyseaLQutktgfbgfJsbHmJhnuv3735yT7fJIDSdu8pcB25BefTmwAdgUVgdOk&imgrefurl=https%3A%2F%2Fwww.99images.com%2Fapps%2Fnews-magazines%2Fpt.civ.dn&tbnid=Sg7LDl5RJAf6VM&vet=10CAcQxiAoBmoXChMI-PX_3e6L9QIVAAAAAB0AAAAAEC0..i&docid=_bNnHUjF9XsmEM&w=512&h=512&itg=1&q=DN&ved=0CAcQxiAoBmoXChMI-PX_3e6L9QIVAAAAAB0AAAAAEC0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PowerAutomate.styles.css" asp-append-version="true" />
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DataNet Comercio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                         @if(User.Identity.IsAuthenticated){
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Logout">Cerrar Sesion</a>
                            </li>
                              <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Productos" asp-action="Index">Productos</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Compras" asp-action="Index">Compras</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Acceder</a>
                            </li>
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Registro">Registro</a>
                            </li>

                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
     <div class="container">
         <div class="text-center py-2">
            <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSM0LAPSksNC6--aTbc_ksK2RzTkj09VL0oztZxBy5BzM4WDuVKBzDQ0tDG7B-1TP0KeA&usqp=CAU" class="img-fluid" alt="Responsive image">
        </div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @if (User.Identity.IsAuthenticated)
    {
        <div class="alert alert-info">
            Usuario  Autenticado
        </div>
    }
    else
    {
        <div class="alert-danger">
            Usuario No Autenticado
        </div>
    }

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DataNet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@9"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>